In [1]:
import numpy as np
import pandas as pd

In [2]:
#统计函数

In [3]:
#pct_change():将每个元素与其前一个元素进行比较，并计算变化百分比
#可用于股票涨幅
s = pd.Series([1,2,3,4,5,4])
print (s.pct_change())

df = pd.DataFrame(np.random.randn(5, 2))
print (df.pct_change())

0         NaN
1    1.000000
2    0.500000
3    0.333333
4    0.250000
5   -0.200000
dtype: float64
          0          1
0       NaN        NaN
1 -0.530655   0.173118
2  1.017478  -5.309034
3 -2.075753  -1.023524
4 -1.892546 -18.829406

In [4]:
#协方差:cov
frame = pd.DataFrame(np.random.randn(10, 5), columns=['a', 'b', 'c', 'd', 'e'])
print (frame['a'].cov(frame['b']))
print (frame.cov())

-0.2874573831014971
          a         b         c         d         e
a  1.810814 -0.287457 -0.911322 -0.498970 -0.189927
b -0.287457  0.439181 -0.017968  0.068681  0.032755
c -0.911322 -0.017968  0.876213 -0.100757  0.179269
d -0.498970  0.068681 -0.100757  1.782454 -0.345489
e -0.189927  0.032755  0.179269 -0.345489  0.432058

In [5]:
#相关性:corr
frame = pd.DataFrame(np.random.randn(10, 5), columns=['a', 'b', 'c', 'd', 'e'])

print (frame['a'].corr(frame['b']))
print (frame.corr())

-0.527344008319726
          a         b         c         d         e
a  1.000000 -0.527344  0.155632  0.397971  0.374048
b -0.527344  1.000000 -0.071851 -0.639287 -0.412682
c  0.155632 -0.071851  1.000000 -0.237534 -0.684340
d  0.397971 -0.639287 -0.237534  1.000000  0.501122
e  0.374048 -0.412682 -0.684340  0.501122  1.000000

In [6]:
#数据排名:rank
'''
Rank支持不同的tie-breaking方法，用方法参数指定 -

average - 并列组平均排序等级min - 组中最低的排序等级max - 组中最高的排序等级first - 按照它们出现在数组中的顺序分配队列


'''
s = pd.Series(np.random.np.random.randn(5), index=list('abcde'))

s['d'] = s['b'] # so there's a tie

print (s.rank())

a    5.0
b    2.5
c    1.0
d    2.5
e    4.0
dtype: float64

In [7]:
#窗口函数

In [8]:
#rolling()
#由于窗口大小为3(window)，前两个元素有空值，第三个元素的值将是n，n-1和n-2元素的平均值。这样也可以应用上面提到的各种函数了
#滚动求平均，第三列为第一、二、三列求平均，第四列为第二、三、四列求平均

df = pd.DataFrame(np.random.randn(10, 4),
index = pd.date_range('1/1/2020', periods=10),
columns = ['A', 'B', 'C', 'D'])

print (df.rolling(window=3).mean())

                   A         B         C         D
2020-01-01       NaN       NaN       NaN       NaN
2020-01-02       NaN       NaN       NaN       NaN
2020-01-03  0.074364  0.053897 -0.211515  0.515425
2020-01-04 -0.273153 -1.279036 -0.340485  0.364998
2020-01-05 -0.107069 -1.299493 -0.717553  0.485319
2020-01-06 -0.341339 -0.637752 -0.437302 -0.146285
2020-01-07 -0.547076 -0.372113 -0.480483  0.493356
2020-01-08 -0.380707 -0.194210 -0.388996  0.530662
2020-01-09 -0.129591 -0.161728 -0.347007 -0.338934
2020-01-10  0.547606 -0.507572 -0.345112 -0.005354

In [9]:
#expanding()
df = pd.DataFrame(np.random.randn(10, 4),
      index = pd.date_range('1/1/2018', periods=10),
      columns = ['A', 'B', 'C', 'D'])
print (df.expanding(min_periods=3).mean())

                   A         B         C         D
2018-01-01       NaN       NaN       NaN       NaN
2018-01-02       NaN       NaN       NaN       NaN
2018-01-03  0.460960 -0.784349 -1.132360 -0.238257
2018-01-04  0.277536 -0.831685 -1.262102 -0.476580
2018-01-05  0.182272 -0.590229 -1.036857 -0.108710
2018-01-06  0.101887 -0.628708 -0.766270 -0.268058
2018-01-07  0.352950 -0.682887 -0.380462 -0.303788
2018-01-08  0.142152 -0.798512 -0.186389 -0.189485
2018-01-09 -0.073560 -0.708649 -0.319429  0.020350
2018-01-10  0.061676 -0.565003 -0.151411  0.132315

In [10]:
#ewm():加权求平均
#指定com，span，halflife参数，并在其上应用适当的统计函数。它以指数形式分配权重。
df = pd.DataFrame(np.random.randn(10, 4),
   index = pd.date_range('1/1/2019', periods=10),
   columns = ['A', 'B', 'C', 'D'])
print (df.ewm(com=0.5).mean())

                   A         B         C         D
2019-01-01 -1.100955 -1.595615 -1.254441  0.518828
2019-01-02 -0.313237  1.136560 -0.298752  0.756470
2019-01-03  0.023288 -0.690952  0.425138  0.521819
2019-01-04  0.195014  0.544654  0.648102  0.479176
2019-01-05  0.249491  0.735538  1.127827  0.727752
2019-01-06 -0.132494 -0.024181  0.949787  0.931074
2019-01-07 -1.173131  0.757954 -0.242187  1.721494
2019-01-08  0.120989  1.157038  0.276332  0.391143
2019-01-09 -0.977723  0.414306  0.491600  0.273511
2019-01-10 -0.392151 -1.040179  1.489604 -0.828179

In [11]:
#聚合函数

In [12]:
#在整个数据框上应用聚合
df = pd.DataFrame(np.random.randn(10, 4),
      index = pd.date_range('1/1/2019', periods=10),
      columns = ['A', 'B', 'C', 'D'])

print("=======================================")
print(df)
r = df.rolling(window=3,min_periods=1) #小于3行就用1行或两行计算平均
print (r)
print("==================使用aggregate=====================")
print(r.aggregate(np.mean))
print("==================使用agg=====================") #更自由
print(r.agg(np.mean))
print("==================rolling.mean=====================")
print(r.mean)

=======================================
                   A         B         C         D
2019-01-01 -1.293855  0.494919  0.620471 -0.111124
2019-01-02  0.075777  0.643535 -0.198724  1.993397
2019-01-03 -0.305060  0.448100 -0.920267 -1.646293
2019-01-04 -0.213103 -1.094308  0.954105  0.509624
2019-01-05 -0.154424 -0.206047  0.655055  0.259356
2019-01-06  1.670836  2.403549 -0.149946  0.404496
2019-01-07 -0.359037 -1.126257  1.489776  0.658069
2019-01-08  1.654380  1.484247  1.968487 -1.102370
2019-01-09  1.267598  1.335294 -1.131915  0.814892
2019-01-10 -1.347467  0.294083 -0.477986  0.138207
Rolling [window=3,min_periods=1,center=False,axis=0]
==================使用aggregate=====================
                   A         B         C         D
2019-01-01 -1.293855  0.494919  0.620471 -0.111124
2019-01-02 -0.609039  0.569227  0.210873  0.941136
2019-01-03 -0.507713  0.528851 -0.166173  0.078660
2019-01-04 -0.147462 -0.000891 -0.054962  0.285576
2019-01-05 -0.224196 -0.284085  0.229631 -0.292438
2019-01-06  0.434436  0.367732  0.486405  0.391159
2019-01-07  0.385792  0.357082  0.664962  0.440640
2019-01-08  0.988727  0.920513  1.102772 -0.013268
2019-01-09  0.854314  0.564428  0.775449  0.123530
2019-01-10  0.524837  1.037875  0.119529 -0.049757
==================使用agg=====================
                   A         B         C         D
2019-01-01 -1.293855  0.494919  0.620471 -0.111124
2019-01-02 -0.609039  0.569227  0.210873  0.941136
2019-01-03 -0.507713  0.528851 -0.166173  0.078660
2019-01-04 -0.147462 -0.000891 -0.054962  0.285576
2019-01-05 -0.224196 -0.284085  0.229631 -0.292438
2019-01-06  0.434436  0.367732  0.486405  0.391159
2019-01-07  0.385792  0.357082  0.664962  0.440640
2019-01-08  0.988727  0.920513  1.102772 -0.013268
2019-01-09  0.854314  0.564428  0.775449  0.123530
2019-01-10  0.524837  1.037875  0.119529 -0.049757
==================rolling.mean=====================
<bound method Rolling.mean of Rolling [window=3,min_periods=1,center=False,axis=0]>

In [13]:
#数据框的单个列上应用聚合
df = pd.DataFrame(np.random.randn(10, 4),
      index = pd.date_range('1/1/2000', periods=10),
      columns = ['A', 'B', 'C', 'D'])
print (df)
print("====================================")
r = df.rolling(window=3,min_periods=1)
print (r['A'].aggregate(np.sum))

                   A         B         C         D
2000-01-01 -1.137486  0.279978 -0.577036  0.957102
2000-01-02  0.683926 -0.615616  0.032559  0.415753
2000-01-03 -0.285042  1.615683 -0.336579 -1.257177
2000-01-04  1.000240  0.293677  0.207423 -0.521480
2000-01-05  0.905271  0.008301  1.043989  0.982925
2000-01-06 -0.180571  0.737062  0.870744 -0.335117
2000-01-07  0.541955  0.973119 -1.550129 -0.969823
2000-01-08 -0.787395  2.389215  0.301332 -0.111942
2000-01-09  1.394573 -0.043966 -1.643328 -0.256981
2000-01-10  0.444269  0.729750  0.003905 -1.574169
====================================
2000-01-01   -1.137486
2000-01-02   -0.453560
2000-01-03   -0.738602
2000-01-04    1.399124
2000-01-05    1.620469
2000-01-06    1.724940
2000-01-07    1.266655
2000-01-08   -0.426010
2000-01-09    1.149134
2000-01-10    1.051447
Freq: D, Name: A, dtype: float64

In [14]:
#在DataFrame的多列上应用聚合
df = pd.DataFrame(np.random.randn(10, 4),
      index = pd.date_range('1/1/2018', periods=10),
      columns = ['A', 'B', 'C', 'D'])
print (df)
print ("==========================================")
r = df.rolling(window=3,min_periods=1)
print (r[['A','B']].aggregate(np.sum))

                   A         B         C         D
2018-01-01  1.117473 -0.012529 -0.499371  0.342571
2018-01-02  0.303148 -0.051190  0.402690 -0.416817
2018-01-03 -0.460032 -0.581008  0.880226 -1.150849
2018-01-04  0.909885  1.203972 -0.609980 -0.021352
2018-01-05 -0.278380 -1.507075  0.713685  1.365269
2018-01-06  0.185622  0.575785  0.568156 -0.346813
2018-01-07  1.251214  1.999563  0.784967  0.002933
2018-01-08 -1.099789 -0.218356 -0.256981  0.548368
2018-01-09 -0.950658  0.695862  1.207278 -0.876128
2018-01-10  0.270309  1.047635  0.710598 -1.398241
==========================================
                   A         B
2018-01-01  1.117473 -0.012529
2018-01-02  1.420621 -0.063719
2018-01-03  0.960589 -0.644727
2018-01-04  0.753001  0.571775
2018-01-05  0.171473 -0.884110
2018-01-06  0.817127  0.272683
2018-01-07  1.158456  1.068273
2018-01-08  0.337046  2.356992
2018-01-09 -0.799234  2.477069
2018-01-10 -1.780139  1.525141

In [15]:
#在DataFrame的单个列上应用多个函数
df = pd.DataFrame(np.random.randn(10, 4),
      index = pd.date_range('2019/01/01', periods=10),
      columns = ['A', 'B', 'C', 'D'])
print (df)

print("==========================================")

r = df.rolling(window=3,min_periods=1)
print (r['A'].aggregate([np.sum,np.mean]))

                   A         B         C         D
2019-01-01  0.744782 -1.133512 -2.018656 -0.089587
2019-01-02  2.617074  0.300369  0.434517  0.558019
2019-01-03 -2.034673 -0.630174 -1.234012 -1.011790
2019-01-04 -1.049423 -0.599574 -0.260075  1.118960
2019-01-05 -1.650773 -1.103783 -0.252099 -0.107100
2019-01-06 -0.021520 -1.483597 -0.211413  2.088204
2019-01-07  1.258709  0.106953  1.368513  0.233114
2019-01-08 -0.033152 -1.279076 -0.284914 -0.853438
2019-01-09 -1.024262  0.728800  0.490782 -1.854768
2019-01-10  0.290089  0.785904 -0.502024  0.658382
==========================================
                 sum      mean
2019-01-01  0.744782  0.744782
2019-01-02  3.361857  1.680928
2019-01-03  1.327183  0.442394
2019-01-04 -0.467022 -0.155674
2019-01-05 -4.734869 -1.578290
2019-01-06 -2.721716 -0.907239
2019-01-07 -0.413584 -0.137861
2019-01-08  1.204037  0.401346
2019-01-09  0.201295  0.067098
2019-01-10 -0.767324 -0.255775

In [16]:
#在DataFrame的多列上应用多个函数
df = pd.DataFrame(np.random.randn(10, 4),
      index = pd.date_range('2020/01/01', periods=10),
      columns = ['A', 'B', 'C', 'D'])

print (df)
print("==========================================")
r = df.rolling(window=3,min_periods=1)
print (r[['A','B']].aggregate([np.sum,np.mean]))

                   A         B         C         D
2020-01-01  0.012525  0.817741 -0.167887 -2.327213
2020-01-02  1.741772  0.503131 -1.037056  1.227876
2020-01-03 -0.326040  0.453097  0.140352 -1.155367
2020-01-04 -0.114948 -0.551539 -1.489564 -0.189890
2020-01-05  2.159243 -1.808623 -1.132955 -1.124364
2020-01-06  0.325527  1.287235 -0.463696 -1.263653
2020-01-07 -1.903412  0.900578 -1.697871 -0.745122
2020-01-08  0.463929  0.613584  0.934367 -0.251968
2020-01-09 -0.617947 -0.793621 -2.235410 -0.951953
2020-01-10  0.980539  0.352668  1.028994 -0.725490
==========================================
                   A                   B
                 sum      mean       sum      mean
2020-01-01  0.012525  0.012525  0.817741  0.817741
2020-01-02  1.754296  0.877148  1.320872  0.660436
2020-01-03  1.428256  0.476085  1.773969  0.591323
2020-01-04  1.300783  0.433594  0.404689  0.134896
2020-01-05  1.718254  0.572751 -1.907065 -0.635688
2020-01-06  2.369821  0.789940 -1.072927 -0.357642
2020-01-07  0.581358  0.193786  0.379190  0.126397
2020-01-08 -1.113956 -0.371319  2.801397  0.933799
2020-01-09 -2.057430 -0.685810  0.720541  0.240180
2020-01-10  0.826521  0.275507  0.172631  0.057544

In [17]:
#将不同的函数应用于DataFrame的不同列
df = pd.DataFrame(np.random.randn(3, 4),
      index = pd.date_range('2020/01/01', periods=3),
      columns = ['A', 'B', 'C', 'D'])
print (df)
print("==========================================")
r = df.rolling(window=3,min_periods=1)
print (r.aggregate({'A' : np.sum,'B' : np.mean}))

                   A         B         C         D
2020-01-01 -0.822080 -1.522264  1.144220 -0.304434
2020-01-02  0.141821 -0.068808  1.218194  1.731111
2020-01-03 -1.377853 -0.320102  0.712144 -1.580537
==========================================
                   A         B
2020-01-01 -0.822080 -1.522264
2020-01-02 -0.680259 -0.795536
2020-01-03 -2.058112 -0.637058

In [18]:
data = pd.read_csv('./data.csv')

In [19]:
data

     地区  新增确诊   累计确诊     治愈    死亡
0    湖北   126  67592  41966  2931
1    广东     1   1351   1209     7
2    河南     0   1272   1242    22
3    浙江     0   1215   1153     1
4    湖南     0   1018    952     4
5    安徽     0    990    970     6
6    江西     0    935    908     1
7    山东     0    758    602     6
8    江苏     0    631    588     -
9    重庆     0    576    513     6
10   四川     0    539    428     3
11  黑龙江     0    481    380    13
12   北京     4    422    298     8
13   上海     1    339    306     3
14   河北     0    318    305     6
15   福建     0    296    278     1
16   广西     0    252    217     2
17   陕西     0    245    224     1
18   云南     0    174    170     2
19   海南     0    168    158     6
20   贵州     0    146    114     2
21   天津     0    136    128     3
22   山西     0    133    126     -
23   辽宁     0    125    106     1
24   香港     0    104     46     2
25   甘肃    11    102     87     2
26   吉林     0     93     89     1
27   新疆     0     76     70     3
28   宁夏     0     75     69     -
29  内蒙古     0     75     65     1
30   台湾     2     44     12     1
31   青海     0     18     18     -
32   澳门     0     10      9     -
33   西藏     0      1      1     -

In [20]:
data = data.replace('-',0)

In [21]:
data['死亡'] = data['死亡'].apply(int)

In [22]:
data

     地区  新增确诊   累计确诊     治愈    死亡
0    湖北   126  67592  41966  2931
1    广东     1   1351   1209     7
2    河南     0   1272   1242    22
3    浙江     0   1215   1153     1
4    湖南     0   1018    952     4
5    安徽     0    990    970     6
6    江西     0    935    908     1
7    山东     0    758    602     6
8    江苏     0    631    588     0
9    重庆     0    576    513     6
10   四川     0    539    428     3
11  黑龙江     0    481    380    13
12   北京     4    422    298     8
13   上海     1    339    306     3
14   河北     0    318    305     6
15   福建     0    296    278     1
16   广西     0    252    217     2
17   陕西     0    245    224     1
18   云南     0    174    170     2
19   海南     0    168    158     6
20   贵州     0    146    114     2
21   天津     0    136    128     3
22   山西     0    133    126     0
23   辽宁     0    125    106     1
24   香港     0    104     46     2
25   甘肃    11    102     87     2
26   吉林     0     93     89     1
27   新疆     0     76     70     3
28   宁夏     0     75     69     0
29  内蒙古     0     75     65     1
30   台湾     2     44     12     1
31   青海     0     18     18     0
32   澳门     0     10      9     0
33   西藏     0      1      1     0

In [23]:
data.agg(np.mean)

新增确诊       4.264706
累计确诊    2373.823529
治愈      1582.558824
死亡        89.558824
dtype: float64